#include "/RPI/Private/SceneCommon.ush"

void BaseVS ( float2 Position : ATTRIBUTE0,
              out float2 UV : TEXCOORD0,
              out float3 ScreenVector : TEXCOORD1,
              out float4 ClipPosition : SV_POSITION )
{
    UV = Position.xy * 0.5 + 0.5;
    ScreenVector = mul ( float4 ( Position.xy, 1, 0 ), View.ScreenToTranslatedWorld ).xyz;
    ClipPosition = float4 ( Position, 0.0, 1.0 );
}